### ISSUE TITLE
Unable to create authtoken

### ISSUE THREAD

**Issue by onlymanas** [apssouza22/java-microservice#10]
During auth-token creation I am getting bellow error.

curl -X POST -vu todo-app:123456 http://localhost:8017/oauth/token -H "Accept: application/json" -d "password=2222&username=gaelle@meama.com=&grant_type=password&scope=write&client_secret=123456&client_id=todo-app"

Error :- {"error":"unauthorized","error_description":"Cannot pass null or empty values to constructor"}

**Comment by apssouza22** [comment]
Where did you get this username / pass?
try to use the one in the Readme

curl -X POST -vu todo-app:123456 http://localhost:8017/oauth/token -H "Accept: application/json" -d "password=1234&username=apssouza22@gmail.com&grant_type=password&scope=write&client_secret=123456&client_id=todo-app"

**Comment by onlymanas** [comment]
I tried with above url and getting same error.

[root@localhost ~]# curl -X POST -vu todo-app:123456 http://localhost:8017/oauth/token -H "Accept: application/json" -d "password=1234&username=apssouza22@gmail.com&grant_type=password&scope=write&client_secret=123456&client_id=todo-app"

* About to connect() to localhost port 8017 (#0)
*   Trying ::1...
* Connected to localhost (::1) port 8017 (#0)
* Server auth using Basic with user 'todo-app'
> POST /oauth/token HTTP/1.1
> Authorization: Basic dG9kby1hcHA6MTIzNDU2
> User-Agent: curl/7.29.0
> Host: localhost:8017
> Accept: application/json
> Content-Length: 115
> Content-Type: application/x-www-form-urlencoded
>
* upload completely sent off: 115 out of 115 bytes
< HTTP/1.1 401
< X-Application-Context: oauth:8017
< Cache-Control: no-store
< Pragma: no-cache
< WWW-Authenticate: Bearer error="unauthorized", error_description="Cannot pass null or empty values to constructor"
< X-Content-Type-Options: nosniff
< X-XSS-Protection: 1; mode=block
< X-Frame-Options: DENY
< Content-Type: application/json;charset=UTF-8
< Transfer-Encoding: chunked
< Date: Mon, 11 Jun 2018 23:36:11 GMT
<
* Connection #0 to host localhost left intact
{"error":"unauthorized","error_description":"Cannot pass null or empty values to constructor"}

**Comment by onlymanas** [comment]
Also I am getting below error while running docker-compose in virtual box.

eureka       | 2018-06-13 17:12:07.947  WARN 93 --- [gistrationTask1] d.c.b.a.c.r.ApplicationRegistrator       : Failed to register application as Application [name=eureka-server, managementUrl=http://eureka:8010/, healthUrl=http://eureka:8010/health/, serviceUrl=http://eureka:8010/] at spring-boot-admin ([http://admin:8026/api/applications, http://localhost:8026/api/applications]): I/O error on POST request for "http://admin:8026/api/applications": Connection refused (Connection refused); nested exception is java.net.ConnectException: Connection refused (Connection refused). Further attempts are logged on DEBUG level.

**Comment by apssouza22** [comment]
For the oauth issue, Can u make sure the user service is running accessing http://localhost:8016/accounts
The admin could not reach the eureka service. Can u access it? http://localhost:8010/
Seems like you are not able to bring up all necessary service from virtual box

**Comment by onlymanas** [comment]
Its working after restart the container. Thank you very much for your support.
