### ISSUE TITLE
Getting error while executing package-projects.sh

### ISSUE THREAD

**Issue by imrahul08** [apssouza22/java-microservice#11]
Hi,

while executing package-projects.sh I am getting following error:

Failed to execute goal io.fabric8:docker-maven-plugin:0.19.0:build (default-cli) on project remainder-service: Execution default-cli of goal io.fabric8:docker-maven-plugin:0.19.0:build failed: JSONObject["auth"] not found. -> [Help 1]

I am using mac and have started Docker.

**Comment by imrahul08** [comment]
I found this https://github.com/ArpNetworking/metrics-aggregator-daemon/pull/96
upgrading plugin to 0.26.0 should have fixed the issue but by doing so I am getting
 [ERROR] Failed to execute goal io.fabric8:docker-maven-plugin:0.20.1:build (default-cli) on project remainder-service: Configured Dockerfile "/Users/rahul/Documents/Java/ms1/java-microservice/./remainder-service/target/dockerimgbuild/Dockerfile" (resolved to "/Users/rahul/Documents/Java/ms1/java-microservice/./remainder-service/target/dockerimgbuild/Dockerfile") doesn't exist

**Comment by imrahul08** [comment]
running command manually by navigating to remainder-service fixed the issue.

**Comment by Shedyk** [comment]
> 
> 
> running command manually by navigating to remainder-service fixed the issue.

@imrahul08 I still get the 'target/dockerimgbuild/Dockerfile doesn't exist' error even if I run the command directly from the reminder-service folder. 
Can you please elaborate how you resolved the issue.
