### ISSUE TITLE
Missing EnableAdminServer annotation 

### ISSUE THREAD

**Issue by Raj150** [apssouza22/java-microservice#12]
Hi, 

It seems the EnableAdminServer custom annotation file and its respective config package is missing  under admin-service.
Can you please add that too.

Regards,
Rajesh Kumar sahoo

**Comment by apssouza22** [comment]
Hi Rajesh, it is already there as you can see here https://github.com/apssouza22/java-microservice/blob/ba8304c3ba36f0c7308c140df035aa78ae1bc806/admin-server/src/main/java/de/codecentric/boot/admin/SpringBootAdminApplication.java#L30

**Comment by Raj150** [comment]
Hi Alexandro,  yes I could see that annotation in that file. But if you look into the import section for this, you can see it is importing from config package which is not exist.
