### ISSUE TITLE
Issue while bringing up docker

### ISSUE THREAD

**Issue by rajesh130687** [apssouza22/java-microservice#14]
Hi @apssouza22 ,

Thanks for a great Repo...
I am trying to bring up the app as mentioned in README.

But i am getting the following error while bringing up docker.

_user         | wait-for-it.sh: waiting 150 seconds for eureka:8010
user         | wait-for-it.sh: timeout occurred after waiting 150 seconds for eureka:8010
user         | ./wait-for-it.sh: /usr/local/bin/start.sh: /bin/bash^M: bad interpreter: No such file or directory
user         | ./wait-for-it.sh: line 175: /usr/local/bin/start.sh: Success
reminder_1   | wait-for-it.sh: waiting 150 seconds for eureka:8010
reminder_1   | wait-for-it.sh: timeout occurred after waiting 150 seconds for eureka:8010
user exited with code 126
reminder_1   | ./wait-for-it.sh: /usr/local/bin/start.sh: /bin/bash^M: bad interpreter: No such file or directory
reminder_1   | ./wait-for-it.sh: line 175: /usr/local/bin/start.sh: Success
todo_reminder_1 exited with code 126
mail         | wait-for-it.sh: waiting 150 seconds for eureka:8010
mail         | wait-for-it.sh: timeout occurred after waiting 150 seconds for eureka:8010
mail         | ./wait-for-it.sh: /usr/local/bin/start.sh: /bin/bash^M: bad interpreter: No such file or directory
gateway_1    | wait-for-it.sh: waiting 150 seconds for eureka:8010
gateway_1    | wait-for-it.sh: timeout occurred after waiting 150 seconds for eureka:8010
mail         | ./wait-for-it.sh: line 175: /usr/local/bin/start.sh: Success
gateway_1    | ./wait-for-it.sh: /usr/local/bin/start.sh: /bin/bash^M: bad interpreter: No such file or directory
gateway_1    | ./wait-for-it.sh: line 175: /usr/local/bin/start.sh: Success
oauth        | wait-for-it.sh: waiting 150 seconds for eureka:8010
oauth        | wait-for-it.sh: timeout occurred after waiting 150 seconds for eureka:8010
oauth        | ./wait-for-it.sh: /usr/local/bin/start.sh: /bin/bash^M: bad interpreter: No such file or directory
mail exited with code 126
todo_gateway_1 exited with code 126
oauth        | ./wait-for-it.sh: line 175: /usr/local/bin/start.sh: Success
oauth exited with code 126_

On further evaluation found the issue was with the wait-for-it.sh file, So created a local copy of it and tried fixing the CRLF issues.

But still i am facing the same issue. Any Thoughts?

Thanks in Advance.

**Comment by apssouza22** [comment]
Hi @rajesh130687, it seems your Eureka is not up. First try to access eureka http://localhost:8010/ if it is not running try to figure out why it is not starting. If u can access it, there is something wrong with your docker network.

**Comment by rajesh130687** [comment]
Again it was due to CRLF issue in a different sh file.
Since i am using windows, i faced this issue. It is resolved now.
