### ISSUE TITLE
Containers giving multiple error while starting. 

### ISSUE THREAD

**Issue by coolest1093** [apssouza22/java-microservice#15]
Error 1:
 0     0    0     0    0     0      0      0 --:--:--  0:00:06 --:--:--     0curl: (7) Failed to connect to elk port 9200: Connection refused
Error 2 (checked app.jar is present in gateway container):
[32;1mgateway_1    |[0m java.io.FileNotFoundException: /app.jar!/BOOT-INF/classes (No such file or directory)
Error 3:
[34mreminder_1   |[0m 2020-02-26 13:50:57.656  WARN 103 --- [ad | producer-1] org.apache.kafka.clients.NetworkClient   : Error while fetching metadata with correlation id 547 : {todo-mail=LEADER_NOT_AVAILABLE}
[docker-orchestrate.log](https://github.com/apssouza22/java-microservice/files/4256057/docker-orchestrate.log)

Attached the startup log when ran "docker-orchestrate.sh"
[docker-orchestrate.log](https://github.com/apssouza22/java-microservice/files/4256060/docker-orchestrate.log)

**Comment by apssouza22** [comment]
1- Your container is not starting properly. Check the ELK container logs. ELK requires a lot memory it can be an issue.
2- No idea why this is happening. 
3 - again your containers are not starting properly. Look at the Kafka and Zookeeper logs
