### ISSUE TITLE
Unable to pull todo/config-server

### ISSUE THREAD

**Issue by vishuvsh47** [apssouza22/java-microservice#7]
Hi @apssouza22 ,

Nice project. I am trying to execute it in my local, but I am facing the below error. Could you please guide me. 

When i execute sh docker-orchestrate.sh

$ sh docker-orchestrate.sh
.
.
.
.
Pulling config (todo/config-server:latest)...
pull access denied for todo/config-server, repository does not exist or may require 'docker login'

**Comment by apssouza22** [comment]
Hi @vishuvsh47 ,
Seems your docker image was not created for the config server. Can you confirm it executing `docker images | grep todo` and see if there is any  todo/config-server?
If the docker image was not created, try to create it executing ` mvn -f ./config-server/pom.xml  -Pdockerimage docker:build`  and check it again with the command above. 

Once you have the docker image created try to run again `$ sh docker-orchestrate.sh`

**Comment by vishuvsh47** [comment]
Hi @apssouza22 ,

Great, that fixed the error, but still I am getting this strange error stating

 [ERROR] Failed to execute goal io.fabric8:docker-maven-plugin:0.24.0:build (default-cli) on project remainder-service: Execution default-cli of goal io.fabric8:docker-maven-plugin:0.24.0:build failed: An API incompatibility was encountered while executing io.fabric8:docker-maven-plugin:0.24.0:build: java.lang.UnsatisfiedLinkError: unknown

I tried googling out and came across a solution that asked me to update the version of the jar. However, it resolved the issue for config-server.  I am now getting it on reminder-service.

I am running on windows 10 and executing this command via gitbash.

**Comment by apssouza22** [comment]
Oh if you are running on Windows, you will need to change the docker host in the poms. 
https://github.com/apssouza22/java-microservice/blob/master/remainder-service/pom.xml#L162
You will see the windows version commented out. 
You will need to confirm which port docker is using, so go to docker settings -> general ->expose daemon on tcp

**Comment by vishuvsh47** [comment]
Thanks @apssouza22 . :)

**Comment by vishuvsh47** [comment]
Guess, having Ubuntu installed is a prerequisite. Coz, lot of shell commands in DockerFile and the paths are relative to ubuntu or centos :) getting failure in windows. Anyways i will use it for reference. 👍

**Comment by apssouza22** [comment]
I haven't really tested it on Windows. Only on Mac and Linux. I will try to make it compatible with Windows later. Tks for the feedback

**Comment by vishuvsh47** [comment]
Nice Project anyways..very useful..covered a lot of concepts :)
