### ISSUE TITLE
How to scale microservice?

### ISSUE THREAD

**Issue by DuyThangDecima** [apssouza22/java-microservice#8]
I don't know how to scale more instance microservice in one node use docker.
Help me.

**Comment by apssouza22** [comment]
In the README there is a section where a talk about scaling.

The command is basically 
`docker-compose -f docker-compose.yml -p PROJECT_NAME up --scale SERVICE_NAME=QTD_OF_INSTANCE`

In our project would be
`docker-compose -f docker-compose.yml -p todo up --scale gateway=2`
