### ISSUE TITLE
(Not issue) Nginx forward to api-gateway

### ISSUE THREAD

**Issue by NDOTV** [apssouza22/java-microservice#9]
I read in nginx config:
upstream backend {
  #ip_hash;
    server **gateway**:8018;
}
1. Why nginx can't find ip of gateway.
2. If api-gateway deploy multi host, how to config nginx
Sorry if it's stupid question.

**Comment by apssouza22** [comment]
Hi,
1 . - You need to add 
```external_links:
      - gatway```
into your docker-compose proxy configuration
2 - As mentioned in the README, You will need to update manually the ports in `default.conf` file inside the proxy(nginx) container and `reload ` Nginx
